import { Router } from 'express';
import authRouter from '../modules/auth/auth.routes';
import agencesRouter from '../modules/agences/agences.routes';
import equipesRouter from '../modules/equipes/equipes.routes';
import groupesRouter from '../modules/groupes-produits/groupes.routes';
import produitsRouter from '../modules/produits/produits.routes';
import utilisateursRouter from '../modules/utilisateurs/utilisateurs.routes';
import agentsRouter from '../modules/agents/agents.routes';
import prospectsRouter from '../modules/prospects/prospects.routes';
import clientsRouter from '../modules/clients/clients.routes';
import comptesRouter from '../modules/comptes/comptes.routes';
import objectifsRouter from '../modules/objectifs/objectifs.routes';
import statsRouter from '../modules/stats/stats.routes';
import logsRouter from '../modules/logs/logs.routes';
import dashboardRouter from '../modules/dashboard/dashboard.routes';
import testRouter from '../modules/test/test.routes';
import recouvrementRouter from '../modules/recouvrement/recouvrement.routes';
import tourneesRouter from '../modules/tournees/tournees.routes';
import collecteRouter from '../modules/collecte/collecte.routes';
import sigRouter from '../modules/sig/sig.routes';
import { notificationsRouter, communicationRouter, integrationRouter } from '../modules/communication/communication.routes';
import comptabiliteRouter from '../modules/comptabilite/comptabilite.routes';
import conformiteRouter from '../modules/conformite/conformite.routes';
import { administrationRouter, securiteRouter } from '../modules/administration/administration.routes';
import analytiqueRouter from '../modules/analytique/analytique.routes';
import documentsRouter from '../modules/documents/documents.routes';
import fichiersRouter from '../modules/fichiers/fichiers.routes';
import rbacRouter from '../modules/rbac/rbac.routes';
import organisationRouter from '../modules/organisation/organisation.routes';
import kycRouter from '../modules/kyc/kyc.routes';
import parametragesRouter from '../modules/parametrages/parametrages.routes';
import creditRouter from '../modules/credit/credit.routes';
import archivesRouter from '../modules/archives/archives.routes';
import interactionsRouter from '../modules/interactions/interactions.routes';

const router = Router();

router.use('/auth', authRouter);
router.use('/agences', agencesRouter);
router.use('/equipes', equipesRouter);
router.use('/groupes-produits', groupesRouter);
router.use('/produits', produitsRouter);
router.use('/utilisateurs', utilisateursRouter);
router.use('/agents', agentsRouter);
router.use('/prospects', prospectsRouter);
router.use('/clients', clientsRouter);
router.use('/comptes', comptesRouter);
router.use('/objectifs', objectifsRouter);
router.use('/stats', statsRouter);
router.use('/logs', logsRouter);
router.use('/dashboard', dashboardRouter);
router.use('/rbac', rbacRouter);
router.use('/organisation', organisationRouter);
router.use('/kyc', kycRouter);
router.use('/parametrages', parametragesRouter);
router.use('/credits', creditRouter);
router.use('/archives', archivesRouter);
router.use('/interactions', interactionsRouter);
router.use('/recouvrement', recouvrementRouter);
router.use('/tournees', tourneesRouter);
router.use('/collecte', collecteRouter);
router.use('/sig', sigRouter);
router.use('/notifications', notificationsRouter);
router.use('/communication', communicationRouter);
router.use('/integration', integrationRouter);
router.use('/comptabilite', comptabiliteRouter);
router.use('/conformite', conformiteRouter);
router.use('/administration', administrationRouter);
router.use('/securite', securiteRouter);
router.use('/analytique', analytiqueRouter);
router.use('/documents', documentsRouter);
router.use('/fichiers', fichiersRouter);
router.use('/test', testRouter);

export default router;
