import type {
  GroupeProduit, Produit, Agence, Equipe, Utilisateur, Agent,
  Prospect, Client, CompteClient, Transaction, Objectif,
} from './types';

// ─── Paramètres ──────────────────────────────────────────────────────────────

export const seedGroupesProduits: GroupeProduit[] = [
  { id: 'gp-1', nom: 'Épargne', description: 'Produits d\'épargne et dépôts', couleur: '#10b981', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'gp-2', nom: 'Micro-assurance', description: 'Couvertures santé et vie', couleur: '#6366f1', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'gp-3', nom: 'Crédit', description: 'Produits de financement', couleur: '#f59e0b', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'gp-4', nom: 'Produits Financiers', description: 'Services de transfert et mobile banking', couleur: '#3b82f6', createdAt: '2025-01-01T00:00:00Z' }
];

// ==========================================
// 2. STRUCTURE DES PRODUITS
// ==========================================
export const seedProduits: Produit[] = [
  // --- GROUPE ÉPARGNE (gp-1) ---
  { id: 'pr-1', nom: 'CECAW Projet', groupeId: 'gp-1', description: 'Épargne bloquée pour la réalisation de projets spécifiques', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-2', nom: 'Dépôts à Terme', groupeId: 'gp-1', description: 'Placements à terme avec taux d\'intérêt négocié et garanti', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-3', nom: 'Bon de Caisse', groupeId: 'gp-1', description: 'Titre de créance nominatif à court ou moyen terme', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-4', nom: 'Collecte Journalière', groupeId: 'gp-1', description: 'Épargne mobile de proximité collectée au quotidien', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-5', nom: 'Compte Salaire', groupeId: 'gp-1', description: 'Compte de dépôt dédié à la domiciliation des revenus professionnels', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-6', nom: 'Compte Courant', groupeId: 'gp-1', description: 'Compte de chèque pour la gestion des transactions quotidiennes', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-7', nom: 'Compte Épargne (ou Compte sur Livret)', groupeId: 'gp-1', description: 'Compte d\'épargne à vue rémunéré disponible à tout moment', actif: true, createdAt: '2025-01-02T00:00:00Z' },

  // --- GROUPE CRÉDIT (gp-3) ---
  { id: 'pr-8', nom: 'Prêt Collecte', groupeId: 'gp-3', description: 'Crédit de trésorerie adossé aux collectes de proximité', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-9', nom: 'Escompte Chèque', groupeId: 'gp-3', description: 'Avance de trésorerie sur chèques remis à l\'encaissement', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-10', nom: 'Préfinancement', groupeId: 'gp-3', description: 'Financement des marchés publics ou des commandes privées', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-11', nom: 'PRO18 Dédouanement', groupeId: 'gp-3', description: 'Crédit d\'accompagnement pour les opérations douanières et logistiques', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-12', nom: 'Crédit Agropastoral', groupeId: 'gp-3', description: 'Financement des campagnes agricoles et activités d\'élevage', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-13', nom: 'Crédit Équipement', groupeId: 'gp-3', description: 'Financement pour l\'acquisition de matériel professionnel et outillage', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-14', nom: 'Crédit Consommation', groupeId: 'gp-3', description: 'Financement des besoins personnels et dépenses familiales', actif: true, createdAt: '2025-01-04T00:00:00Z' },
  { id: 'pr-15', nom: 'Avances sur Stocks', groupeId: 'gp-3', description: 'Financement sur gage des marchandises stockées', actif: true, createdAt: '2025-01-04T00:00:00Z' },

  // --- GROUPE FINANCIERS (gp-4) ---
  { id: 'pr-16', nom: 'CECAW Mobile', groupeId: 'gp-4', description: 'Application de banque en ligne et gestion de compte à distance', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-17', nom: 'Transferts Internationaux', groupeId: 'gp-4', description: 'Réception et envoi de fonds à l\'international', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-18', nom: 'MTN Mobile Money', groupeId: 'gp-4', description: 'Passerelle de dépôt et retrait via le réseau MTN', actif: true, createdAt: '2025-01-02T00:00:00Z' },
  { id: 'pr-19', nom: 'Orange Money', groupeId: 'gp-4', description: 'Passerelle de dépôt et retrait via le réseau Orange', actif: true, createdAt: '2025-01-02T00:00:00Z' },

  // --- GROUPE MICRO-ASSURANCE (gp-2) ---
  { id: 'pr-20', nom: 'PRO28', groupeId: 'gp-2', description: 'Contrat de couverture spécifique et assistance', actif: true, createdAt: '2025-01-03T00:00:00Z' },
  { id: 'pr-21', nom: 'Omega CEJ', groupeId: 'gp-2', description: 'Prévoyance et couverture des risques spécifiques aux jeunes entrepreneurs', actif: true, createdAt: '2025-01-03T00:00:00Z' },
  { id: 'pr-22', nom: 'CECAW Vie', groupeId: 'gp-2', description: 'Assurance décès invalidité et épargne de prévoyance funéraire', actif: true, createdAt: '2025-01-03T00:00:00Z' }
];

export const seedAgences: Agence[] = [
  { id: 'ag-1', nom: 'Agence Dakar', ville: 'Douala', adresse: 'Quartier Dakar', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-2', nom: 'Agence Congo', ville: 'Douala', adresse: 'Marché Congo', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-3', nom: 'Agence Mokolo', ville: 'Yaoundé', adresse: 'Marché Mokolo', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-4', nom: 'Agence Djemoun', ville: 'Foumban', adresse: 'Quartier Djemoun', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-5', nom: 'Agence Bonaberi', ville: 'Douala', adresse: 'Bonaberi, Ancienne Route', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-6', nom: 'Agence Dschang', ville: 'Dschang', adresse: 'Centre-ville, Dschang', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-7', nom: 'Agence Etoudi', ville: 'Yaoundé', adresse: 'Quartier Etoudi', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-8', nom: 'Agence Bepanda', ville: 'Douala', adresse: 'Bepanda Tonnerre', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-9', nom: 'Agence Bonfils', ville: 'Yaoundé', adresse: 'Carrefour Bonfils', actif: true, createdAt: '2025-01-01T00:00:00Z' },
  { id: 'ag-10', nom: 'Agence Akwa', ville: 'Douala', adresse: 'Marché Congo, Akwa', actif: true, createdAt: '2025-01-01T00:00:00Z' }
];

export const seedUtilisateurs: Utilisateur[] = [
  // --- Utilisateurs Exemples (Rattachés par défaut à ag-1) ---
  { id: 'u-1', nom: 'Mvondo', prenom: 'Jean', email: 'j.mvondo@cecaw.cm', role: 'agent', fonction: 'Agent de collecte', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-2', nom: 'Kamga', prenom: 'Eric', email: 'e.kamga@cecaw.cm', role: 'agent', fonction: 'Agent terrain', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-3', nom: 'Talla', prenom: 'Pierre', email: 'p.talla@cecaw.cm', role: 'agent', fonction: 'Agent de proximité', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-4', nom: 'Ngassa', prenom: 'Marie', email: 'm.ngassa@cecaw.cm', role: 'manager', fonction: 'Responsable agence', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-5', nom: 'Bopda', prenom: 'Lionel', email: 'l.bopda@cecaw.cm', role: 'backoffice', fonction: 'Caissier principal', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-6', nom: 'Admin', prenom: 'Système', email: 'admin@cecaw.cm', role: 'admin', fonction: 'Administrateur système', agenceId: 'ag-1', equipeId: '', actif: true, createdAt: '2025-01-01T00:00:00Z' },

  // --- AGENCE DAKAR (ag-1) ---
  { id: 'u-7', nom: 'Nana Ngatchou', prenom: 'Winnie Didine', email: 'winniedidine.nanangatchou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-8', nom: 'Moukou Enongue', prenom: 'Brice Deblondo', email: 'bricedeblondo.moukouenongue@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-9', nom: 'Njoumou', prenom: 'Annie Guilène', email: 'annieguilene.njoumou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-10', nom: 'Younou', prenom: 'Simo', email: 'simo.younou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-11', nom: 'Teuga Domgang', prenom: 'Casimir Sarah', email: 'casimirsarah.teugadomgang@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-12', nom: 'Betegne', prenom: 'Luc Vianey', email: 'lucvianey.betegne@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-1', equipeId: 'eq-1', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-13', nom: 'Makam', prenom: 'Sonia Belkie', email: 'soniabelkie.makam@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-1', equipeId: 'eq-4', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-14', nom: 'Nkenfack', prenom: 'Mirabelle Clementine', email: 'mirabelleclementine.nkenfack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-15', nom: 'Siewe', prenom: 'épse Tsague Laure', email: 'laure.siewe@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-16', nom: 'Tangantchoua', prenom: 'épse Zoa Sylvie', email: 'sylvie.tangantchoua@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-17', nom: 'Baran', prenom: 'épse Fram A Toman Solange', email: 'solange.baran@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-18', nom: 'Tomani', prenom: 'Carine Dore', email: 'carinedore.tomani@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-19', nom: 'Njepgang Tchatchoua', prenom: 'Chamberline', email: 'chamberline.njepgangtchatchoua@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-20', nom: 'Jingang', prenom: 'Viviane Mimi', email: 'vivianemimi.jingang@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-21', nom: 'Tchakam Ngako', prenom: 'Modeste', email: 'modeste.tchakamngako@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-22', nom: 'Youdeu', prenom: 'Rosaline Aimee', email: 'rosalineaimee.youdeu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-23', nom: 'Theuaho', prenom: 'Melanie Chantale', email: 'melaniechantale.theuaho@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-24', nom: 'Tsafack Tankeu', prenom: 'Doriane Prisca', email: 'dorianeprisca.tsafacktankeu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-25', nom: 'Tchouassi Ngako', prenom: 'Gabel', email: 'gabel.tchouassingako@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-26', nom: 'Ngako Djomeni', prenom: 'Larissa', email: 'larissa.ngakodjomeni@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-27', nom: 'Akouemo Nounouim', prenom: 'Blandine', email: 'blandine.akouemonounouim@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-28', nom: 'Youaleu', prenom: 'Darelle Cedia', email: 'darellecedia.youaleu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-29', nom: 'Ngo Iloga', prenom: 'Jeannette Amandine', email: 'jeannetteamandine.ngoiloga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-30', nom: 'Nguedeu', prenom: 'Hugues Marin', email: 'huguesmarin.nguedeu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-31', nom: 'Belle Otti', prenom: 'Regine', email: 'regine.belleotti@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-32', nom: 'Djaba Tchouba', prenom: 'Darlaine', email: 'darlaine.djabatchouba@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-33', nom: 'Mbeugang', prenom: 'Fernandez Dupplexe', email: 'fernandezdupplexe.mbeugang@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-1', equipeId: 'eq-3', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-34', nom: 'Ndiang Korot', prenom: 'Antoinetta', email: 'antoinetta.ndiangkorot@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-1', equipeId: 'eq-4', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-35', nom: 'Betssi', prenom: 'Solange épse Fouafack', email: 'solange.betssi@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-1', equipeId: 'eq-2', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-36', nom: 'Nkouda Tadatsin', prenom: 'Isabelle', email: 'isabelle.nkoudatadatsin@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-1', equipeId: 'eq-2', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-37', nom: 'Kouaong Noubissie', prenom: 'Charnele', email: 'charnele.kouaongnoubissie@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-1', equipeId: 'eq-2', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE CONGO (ag-2) ---
  { id: 'u-38', nom: 'Djoussi Ngasse', prenom: 'Cecile Olivia', email: 'cecileolivia.djoussingasse@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-39', nom: 'Mounet', prenom: 'Girelle', email: 'girelle.mounet@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-40', nom: 'Tete Mbangue Sondi', prenom: 'Anne', email: 'anne.tetembanguesondi@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-41', nom: 'Nguebou', prenom: 'Kevine', email: 'kevine.nguebou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-42', nom: 'Tchouanmo Mba', prenom: 'Dimitri Junior', email: 'dimitrijunior.tchouanmomba@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-43', nom: 'Nguetcheu Toukep', prenom: 'Rickel', email: 'rickel.nguetcheutoukep@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-2', equipeId: 'eq-5', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-44', nom: 'Kenmogne Fouyong', prenom: 'Paule Michèle', email: 'paulemichele.kenmognefouyong@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-2', equipeId: 'eq-8', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-45', nom: 'Madefo', prenom: 'Genevieve', email: 'genevieve.madefo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-46', nom: 'Mewoumbe', prenom: 'Annie', email: 'annie.mewoumbe@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-47', nom: 'Mefo', prenom: 'Mireille', email: 'mireille.mefo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-48', nom: 'Faha', prenom: 'Georgette', email: 'georgette.faha@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-49', nom: 'Talin', prenom: 'Jeanne', email: 'jeanne.talin@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-50', nom: 'Massu', prenom: 'Christelle Jade', email: 'christellejade.massu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-51', nom: 'Ekame', prenom: 'Louise', email: 'louise.ekame@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-52', nom: 'Touadjeu Tchangue', prenom: 'Elisabeth', email: 'elisabeth.touadjeutchangue@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-53', nom: 'Ngoune F', prenom: 'Melanie', email: 'melanie.ngounef@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-54', nom: 'Kaghogue', prenom: 'Noel Eveline', email: 'noeleveline.kaghogue@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-55', nom: 'Tchiadjeu Moungoue', prenom: 'Tatiana', email: 'tatiana.tchiadjeumoungoue@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-56', nom: 'Kapche Siliedje', prenom: 'Marie Doriane', email: 'mariedoriane.kapchesiliedje@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-57', nom: 'Djoumessi Depoupo', prenom: 'Dorcreche', email: 'dorcreche.djoumessidepoupo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-58', nom: 'Wasso Fankam', prenom: 'Steve', email: 'steve.wassofankam@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-59', nom: 'Simen Tchoufong', prenom: 'Viviane', email: 'viviane.simentchoufong@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-60', nom: 'Djoumbat', prenom: 'Ariane Victoire', email: 'arianevictoire.djoumbat@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-61', nom: 'Nguetchayou', prenom: 'Larissa Carine', email: 'larissacarine.nguetchayou@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-2', equipeId: 'eq-7', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-62', nom: 'Tchatche Djamie', prenom: 'Vanessa', email: 'vanessa.tchatchedjamie@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-2', equipeId: 'eq-8', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE AKWA (ag-10) ---
  { id: 'u-63', nom: 'Nelly Djengou', prenom: 'Nsia Esther', email: 'nsiaesther.nellydjengou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-64', nom: 'Keubou Wagou', prenom: 'Nina épse Kengue', email: 'ninakengue.keubouwagou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-65', nom: 'Kenfack Fokou', prenom: 'Elsa Ebenezere', email: 'elsaebenezere.kenfackfokou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-66', nom: 'Nanfack', prenom: 'Ornelle Verdis', email: 'ornelleverdis.nanfack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-67', nom: 'Tatio', prenom: 'Evaw Junior', email: 'evawjunior.tatio@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-68', nom: 'Tchouassi', prenom: 'Therese Maurine', email: 'theresemaurine.tchouassi@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-69', nom: 'Ngadoum Debora', prenom: 'Prudence', email: 'prudence.ngadoumdebora@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-70', nom: 'Tchanou Kamnang', prenom: 'Austin', email: 'austin.tchanoukamnang@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-10', equipeId: 'eq-9', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-71', nom: 'Ngounou Koyue', prenom: 'Dorice Christian', email: 'doricechristian.ngounoukoyue@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-10', equipeId: 'eq-12', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-72', nom: 'Djuidje', prenom: 'Debaura', email: 'debaura.djuidje@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-73', nom: 'Megha Fopa', prenom: 'Rosine', email: 'rosine.meghafopa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-74', nom: 'Djomako', prenom: 'Guillaine', email: 'guillaine.djomako@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-75', nom: 'Mbenty', prenom: 'Lucie Laure', email: 'lucielaure.mbenty@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-76', nom: 'Guiadjou', prenom: 'Chanceline', email: 'chanceline.guiadjou@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-77', nom: 'Sendjeu Tchanga', prenom: 'Wulliamide', email: 'wulliamide.sendjeutchanga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-78', nom: 'Temfack Tsapzang', prenom: 'Christel', email: 'christel.temfacktsapzang@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-79', nom: 'Yetgni', prenom: 'Christelle Carole', email: 'christellecarole.yetgni@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-80', nom: 'Ndzie', prenom: 'Bertille', email: 'bertille.ndzie@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-81', nom: 'Mamba Nyambi', prenom: 'Madeleine', email: 'madeleine.mambanyambi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-82', nom: 'Fobasso Tamguelong', prenom: 'Ginette', email: 'ginette.fobassotamguelong@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-83', nom: 'Yougmegni Gankam', prenom: 'Carole', email: 'carole.yougmegnigankam@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-84', nom: 'Magnigue Kamga', prenom: 'Sandrine', email: 'sandrine.magniguekamga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-85', nom: 'Doukeu Kuetchoua', prenom: 'Judith Laure', email: 'judithlaure.doukeukuetchoua@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-86', nom: 'Fokou Obein', prenom: 'Lebien', email: 'lebien.fokouobein@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-87', nom: 'Wandji', prenom: 'Raissa', email: 'raissa.wandji@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-88', nom: 'Ananfack Kemtsop', prenom: 'Andre', email: 'andre.ananfackkemtsop@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-89', nom: 'Nguimatsia Kemgang', prenom: 'Mavel', email: 'mavel.nguimatsiakemgang@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-10', equipeId: 'eq-11', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-90', nom: 'Tanmi Nana', prenom: 'Emma Léonie', email: 'emmaleonie.tanminana@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-10', equipeId: 'eq-12', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-91', nom: 'Kuate Ngamgne', prenom: 'Sandrine', email: 'sandrine.kuatengamgne@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-10', equipeId: 'eq-10', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-92', nom: 'Ndiang Christine', prenom: 'Linda', email: 'linda.ndiangchristine@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-10', equipeId: 'eq-10', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-93', nom: 'Ndoya Nganko', prenom: 'Leaticia Diane', email: 'leaticiadiane.ndoyanganko@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-10', equipeId: 'eq-10', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE MOKOLO (ag-3) ---
  { id: 'u-94', nom: 'Mekuaté Siledje', prenom: 'Hermine flore', email: 'hermineflore.mekuatesiledje@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-95', nom: 'Kamaha Yamdjeu', prenom: 'Horly Brice', email: 'horlybrice.kamahayamdjeu@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-96', nom: 'Nsing Um', prenom: 'Emmanuel', email: 'emmanuel.nsingum@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-97', nom: 'Abanda Meboni', prenom: 'Jeanne Dorcas', email: 'jeannedorcas.abandameboni@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-98', nom: 'Djuidje', prenom: 'Rayssa Noelle', email: 'rayssanoelle.djuidje@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-99', nom: 'Bessala Ndzana', prenom: 'Herman', email: 'herman.bessalandzana@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-100', nom: 'Nkammen Djami', prenom: 'Pachelle', email: 'pachelle.nkammendjami@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-3', equipeId: 'eq-13', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-101', nom: 'Atonmezing', prenom: 'Blandine', email: 'blandine.atonmezing@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-3', equipeId: 'eq-16', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-102', nom: 'Wansi', prenom: 'Nicole', email: 'nicole.wansi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-103', nom: 'Kembou', prenom: 'Nicole', email: 'nicole.kembou@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-104', nom: 'Letieu', prenom: 'Chamberline', email: 'chamberline.letieu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-105', nom: 'Guemo', prenom: 'Athalie', email: 'athalie.guemo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-106', nom: 'Toukem', prenom: 'Anne', email: 'anne.toukem@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-107', nom: 'Mfouche', prenom: 'Rosalie', email: 'rosalie.mfouche@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-108', nom: 'Amekeu', prenom: 'Stevie', email: 'stevie.amekeu@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-109', nom: 'Apoupo', prenom: 'Gaelle', email: 'gaelle.apoupo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-110', nom: 'Ngwang Haggai', prenom: 'Sandrine', email: 'sandrine.ngwanghaggai@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-111', nom: 'Madjeumo', prenom: 'Victorine', email: 'victorine.madjeumo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-112', nom: 'Magne', prenom: 'Judith', email: 'judith.magne@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-113', nom: 'Djouodoug', prenom: 'épse Tambeck Chimene', email: 'chimene.djouodoug@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-114', nom: 'Makougoum Takam', prenom: 'Sorelle Nickelle', email: 'sorellenickelle.makougoumtakam@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-115', nom: 'Tiazia', prenom: 'Roseline', email: 'roseline.tiazia@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-116', nom: 'Mamo Tchoffo', prenom: 'Guylene', email: 'guylene.mamotchoffo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-117', nom: 'Teumou Tchamba', prenom: 'Nafissetou', email: 'nafissetou.teumoutchamba@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-118', nom: 'Kuemi', prenom: 'Vanessa Colinette', email: 'vanessacolinette.kuemi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-3', equipeId: 'eq-15', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-119', nom: 'Tchuenguem Modjo', prenom: 'Laure', email: 'laure.tchuenguemmodjo@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-3', equipeId: 'eq-16', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-120', nom: 'Tondji Kouayip', prenom: 'Ghislaine', email: 'ghislaine.tondjikouayip@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-3', equipeId: 'eq-14', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-121', nom: 'Meibou Gwokam', prenom: 'Vinet Ilaria', email: 'vinetilaria.meibougwokam@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-3', equipeId: 'eq-14', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-122', nom: 'Zefack Tonleu', prenom: 'Miriam Marvelle', email: 'miriammarvelle.zefacktonleu@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-3', equipeId: 'eq-14', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE DJEMOUN (ag-4) ---
  { id: 'u-123', nom: 'Atemazem Tsanang', prenom: 'Francky Jaures', email: 'franckyjaures.atemazemtsanang@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-124', nom: 'Kamdem', prenom: 'Parfait Valentin', email: 'parfaitvalentin.kamdem@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-125', nom: 'Noulah Tchouteizo', prenom: 'Paule Prudence', email: 'pauleprudence.noulahtchouteizo@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-126', nom: 'Kepseu Sahou', prenom: 'Landry', email: 'landry.kepseusahou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-127', nom: 'Kameni Kouendjou', prenom: 'Ines', email: 'ines.kamenikouendjou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-128', nom: 'Djeunang Foteu', prenom: 'Wilson Bruno', email: 'wilsonbruno.djeunangfoteu@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-129', nom: 'Fosso Mokam', prenom: 'Sandra', email: 'sandra.fossomokam@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-130', nom: 'Talla', prenom: 'Aloick Idriss', email: 'aloickidriss.talla@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-131', nom: 'Fozoue', prenom: 'Merveille Kevine', email: 'merveillekevine.fozoue@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-4', equipeId: 'eq-17', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-132', nom: 'Tchinda Tsopa', prenom: 'épse Difo Larissa', email: 'larissa.tchindatsopa@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-4', equipeId: 'eq-20', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-133', nom: 'Guiadem', prenom: 'Nadine Benedicte', email: 'nadinebenedicte.guiadem@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-134', nom: 'Segning Nanfa', prenom: 'Egwige L', email: 'egwigel.segningnanfa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-135', nom: 'Jipgang Chendjou', prenom: 'Octavia', email: 'octavia.jipgangchendjou@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-136', nom: 'Nodem Nanfa', prenom: 'Marie', email: 'marie.nodemnanfa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-137', nom: 'Magne Poaka', prenom: 'Julienne Eloise', email: 'julienneeloise.magnepoaka@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-138', nom: 'Ngo Ngwem', prenom: 'Marie Natacha', email: 'marienatacha.ngongwem@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-139', nom: 'Tchouga', prenom: 'Franck Alex', email: 'franckalex.tchouga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-140', nom: 'Sofeu Fotsi', prenom: 'Lothilde Adrielle', email: 'lothildeadrielle.sofeufotsi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-141', nom: 'Talla Makoutsing', prenom: 'Velene Sukissa', email: 'velenesukissa.tallamakoutsing@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-142', nom: 'Synthia Berinyuy', prenom: 'Ngivelon', email: 'ngivelon.synthiaberinyuy@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-143', nom: 'Lele Tchomtchoua', prenom: 'Sandra Danoucia', email: 'sandradanoucia.leletchomtchoua@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-144', nom: 'Segning Diffo', prenom: 'Edith Laure', email: 'edithlaure.segningdiffo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-145', nom: 'Magokeng Kenne', prenom: 'Lavissa Sonia', email: 'lavissasonia.magokengkenne@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-146', nom: 'Meboue Peubong', prenom: 'Rosine Diane', email: 'rosinediane.mebouepeubong@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-147', nom: 'Mantho', prenom: 'Duchelle Fabiola', email: 'duchellefabiola.mantho@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-148', nom: 'Mouoffokouo Poukam', prenom: 'Elisabeth', email: 'elisabeth.mouoffokouopoukam@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-149', nom: 'Meche Bogne', prenom: 'Mireille', email: 'mireille.mechebogne@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-150', nom: 'Ngomdop', prenom: 'Lucresse Nicaise', email: 'lucressenicaise.ngomdop@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-151', nom: 'Tebu Lele', prenom: 'Lucresse Nicaise', email: 'lucressenicaise.tebulele@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-152', nom: 'Mebouet', prenom: 'épse Pone', email: 'pone.mebouet@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-4', equipeId: 'eq-19', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-153', nom: 'Tsafack', prenom: 'Carine Pélagie', email: 'carinepelagie.tsafack@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-4', equipeId: 'eq-20', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-154', nom: 'Metueno Dzeboa', prenom: 'épse Tiako Larissa', email: 'larissa.metuenodzeboa@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-4', equipeId: 'eq-18', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-155', nom: 'Djuissi Ndungne', prenom: 'Christelle', email: 'christelle.djuissindungne@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-4', equipeId: 'eq-18', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE BONABERI (ag-5) ---
  { id: 'u-156', nom: 'Tchiechie Tchaeha', prenom: 'Franklin Nelson', email: 'franklinnelson.tchiechietchaeha@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-5', equipeId: 'eq-21', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-157', nom: 'Tchiffo Soctio', prenom: 'Franck Omer', email: 'franckomer.tchiffosoctio@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-5', equipeId: 'eq-21', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-158', nom: 'Ndema Nkrumah', prenom: 'Gwet', email: 'gwet.ndemankrumah@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-5', equipeId: 'eq-21', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-159', nom: 'Tchako', prenom: 'Dorkas', email: 'dorkas.tchako@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-5', equipeId: 'eq-24', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-160', nom: 'Djabou', prenom: 'Viviane', email: 'viviane.djabou@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-161', nom: 'Mouga', prenom: 'Tatiane', email: 'tatiane.mouga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-162', nom: 'Anafack Maguimekem', prenom: 'Madeleine', email: 'madeleine.anafackmaguimekem@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-163', nom: 'Tchapda', prenom: 'Stephanie', email: 'stephanie.tchapda@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-164', nom: 'Tchouboume', prenom: 'Leocadie Raissa', email: 'leocadieraisa.tchouboume@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-165', nom: 'Tchakoutio', prenom: 'Charlie', email: 'charlie.tchakoutio@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-166', nom: 'Diffo Saha', prenom: 'Zaviera', email: 'zaviera.diffosaha@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-167', nom: 'Nguefa', prenom: 'Genevieve Michael', email: 'genevievemichael.nguefa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-168', nom: 'Foyet', prenom: 'Oscarine', email: 'oscarine.foyet@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-169', nom: 'Kwedi Mbappe', prenom: 'Elise Francine', email: 'elisefrancine.kwedimbappe@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-170', nom: 'Kouobou Moaffo', prenom: 'Catherine Sonia', email: 'catherinesonia.kouoboumoaffo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-171', nom: 'Fossi Makuetche', prenom: 'Emmanuelle', email: 'emmanuelle.fossimakuetche@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-172', nom: 'Yamgoh', prenom: 'Perpetual', email: 'perpetual.yamgoh@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-173', nom: 'Lemoukong', prenom: 'Linda Sorelle', email: 'lindasorelle.lemoukong@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-174', nom: 'Yoneu Ekomo', prenom: 'Geordane Morelle', email: 'geordanemorelle.yoneuekomo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-175', nom: 'Wague Donfack', prenom: 'Pelagie', email: 'pelagie.wagnedonfack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-176', nom: 'Poupo', prenom: 'Alice', email: 'alice.poupo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-5', equipeId: 'eq-23', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-177', nom: 'Tchienou Tchamba', prenom: 'Joelle', email: 'joelle.tchienoutchamba@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-5', equipeId: 'eq-24', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-178', nom: 'Enyegue', prenom: 'Madeleine Claudia', email: 'madeleineclaudia.enyegue@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-5', equipeId: 'eq-22', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-179', nom: 'Yoba', prenom: 'Christelle Laure', email: 'christellelaure.yoba@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-5', equipeId: 'eq-22', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-180', nom: 'Zepop Nzokizep', prenom: 'Yamine Martinez', email: 'yaminemartinez.zepopnzokizep@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-5', equipeId: 'eq-22', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE DSCHANG (ag-6) ---
  { id: 'u-181', nom: 'Kahou Tsafack', prenom: 'Annicet', email: 'annicet.kahoutsafack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-182', nom: 'Maffo Dongfack', prenom: 'Aline Gael', email: 'alinegael.maffodongfack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-183', nom: 'Azapmo Tonfack', prenom: 'Etienne Junior', email: 'etiennejunior.azapmotonfack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-184', nom: 'Tchassi Leukeumo', prenom: 'William Hermann', email: 'williamhermann.tchassileukeumo@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-185', nom: 'Wintcheu Wortchoko', prenom: 'Julienne Sorelle', email: 'juliennesorelle.wintcheuwortchoko@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-186', nom: 'Tadondje Momo', prenom: 'Bonita Charonne', email: 'bonitacharonne.tadondjemomo@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-187', nom: 'Donfack Lekefack', prenom: 'Paganel', email: 'paganel.donfacklekefack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-6', equipeId: 'eq-25', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-188', nom: 'Makamtchop', prenom: 'Virginie', email: 'virginie.makamtchop@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-6', equipeId: 'eq-28', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-189', nom: 'Tsafack Mekemjio', prenom: 'Ernestine', email: 'ernestine.tsafackmekemjio@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-190', nom: 'Dongmo Vouffo', prenom: 'Benjeamine', email: 'benjeamine.dongmovouffo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-191', nom: 'Teufack', prenom: 'Quelisa Ayssa', email: 'quelisaayssa.teufack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-192', nom: 'Tsafong', prenom: 'Christelle', email: 'christelle.tsafong@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-193', nom: 'Akiteu Minthet', prenom: 'Lea', email: 'lea.akiteuminthet@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-194', nom: 'Angue Woussi', prenom: 'Gaelle', email: 'gaelle.anguewoussi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-195', nom: 'Tchekouo', prenom: 'Hermine', email: 'hermine.tchekouo@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-196', nom: 'Lekane Tsafack', prenom: 'Justine', email: 'justine.lekanetsafack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-197', nom: 'Metampa', prenom: 'Lucresse Charnelle', email: 'lucressecharnelle.metampa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-198', nom: 'Manenang Jeufack', prenom: 'Jidicaelle Charlotte', email: 'jidicaellecharlotte.manenangjeufack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-199', nom: 'Nague Tonfack', prenom: 'Stevie Charnelle', email: 'steviecharnelle.naguetonfack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-200', nom: 'Temfack', prenom: 'Nadine Christelle', email: 'nadinechristelle.temfack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-201', nom: 'Donfack', prenom: 'Valdes', email: 'valdes.donfack@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-202', nom: 'Assonfack Djoumessi', prenom: 'Madeleine', email: 'madeleine.assonfackdjoumessi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-203', nom: 'Feumo Delisa', prenom: 'An Mabelle', email: 'anmabelle.feumodelisa@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-204', nom: 'Donfack Zebaze', prenom: 'Staline Lakene', email: 'stalinelakene.donfackzebaze@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-205', nom: 'Chimini', prenom: 'Flauriane Lauraine', email: 'flaurianelauraine.chimini@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-6', equipeId: 'eq-27', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-206', nom: 'Komene Manefouet', prenom: 'Jeanine épse Kenfack', email: 'jeanine.komenemanefouet@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-6', equipeId: 'eq-28', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-207', nom: 'Matchidjio', prenom: 'Mariane Nadine', email: 'marianenadine.matchidjio@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-6', equipeId: 'eq-26', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-208', nom: 'Leussi Chuipa', prenom: 'Ornella Audrey', email: 'ornellaaudrey.leussichuipa@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-6', equipeId: 'eq-26', actif: true, createdAt: '2025-01-05T00:00:00Z' },

  // --- AGENCE ETOUDI (ag-7) ---
  { id: 'u-209', nom: 'Olomo Amimba', prenom: 'Barnabe Vivien', email: 'barnabevivien.olomoamimba@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-210', nom: 'Essono Fowo', prenom: 'Yann Maxime', email: 'yannmaxime.essonofowo@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-211', nom: 'Ambomo', prenom: 'Alexandre Gordon', email: 'alexandregordon.ambomo@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-212', nom: 'Nongni', prenom: 'Idris Roberto', email: 'idrisroberto.nongni@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-213', nom: 'Eboutou', prenom: 'Paul Yannick', email: 'paulyannick.eboutou@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-214', nom: 'Aboya', prenom: 'Gladys Madeleine', email: 'gladysmadeleine.aboya@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-215', nom: 'Abidime Emboueme', prenom: 'Nadège', email: 'nadege.abidimeemboueme@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-216', nom: 'Tjemi', prenom: 'Grace Cécile', email: 'gracececile.tjemi@cecaw.cm', role: 'agent', fonction: 'Gestionnaire de credit classique', agenceId: 'ag-7', equipeId: 'eq-29', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-217', nom: 'Chouna', prenom: 'Gwladys epse Fossa', email: 'gwladys.chouna@cecaw.cm', role: 'backoffice', fonction: 'Guichetière', agenceId: 'ag-7', equipeId: 'eq-32', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-218', nom: 'Nanga Ombede', prenom: 'Cecile', email: 'cecile.nangaombede@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-219', nom: 'Ongolo Ombede', prenom: 'Brigitte Nadine', email: 'brigittenadine.ongoloombede@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-220', nom: 'Batipamen', prenom: 'Jacqueline', email: 'jacqueline.batipamen@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-221', nom: 'Bella Wono', prenom: 'Pauline', email: 'pauline.bellawono@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-222', nom: 'Essengue', prenom: 'Anne Nadine', email: 'annenadine.essengue@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-223', nom: 'Tsama Belibi', prenom: 'Cecile Nadege', email: 'cecilenadege.tsamabelibi@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-224', nom: 'Yana Nyemb', prenom: 'Ariane', email: 'ariane.yananyemb@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-225', nom: 'Mvotto Andinga', prenom: 'Morane', email: 'morane.mvottoandinga@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-226', nom: 'Njeunko', prenom: 'epse Noutat Bergeline', email: 'bergeline.njeunko@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-227', nom: 'Moloh Onana', prenom: 'Amandine Pascaline', email: 'amandinepascaline.molohonana@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-228', nom: 'Bediang', prenom: 'Merveille Rachel', email: 'merveillerachel.bediang@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-229', nom: 'Ngah', prenom: 'Elisabeth Clarisse', email: 'elisabethclarisse.ngah@cecaw.cm', role: 'agent', fonction: 'Commercial', agenceId: 'ag-7', equipeId: 'eq-31', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-230', nom: 'Kana Mawamba', prenom: 'Léa', email: 'lea.kanamawamba@cecaw.cm', role: 'manager', fonction: 'Superviseur collecte', agenceId: 'ag-7', equipeId: 'eq-32', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-231', nom: 'Fosso Anafack', prenom: 'Ariane epse Ngueko', email: 'ariane.fossoanafack@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-7', equipeId: 'eq-30', actif: true, createdAt: '2025-01-05T00:00:00Z' },
  { id: 'u-232', nom: 'Amombo Etoundi', prenom: 'Shanel', email: 'shanel.amomboetoundi@cecaw.cm', role: 'agent', fonction: 'Gestionnaire prêt collecte', agenceId: 'ag-7', equipeId: 'eq-30', actif: true, createdAt: '2025-01-05T00:00:00Z' }
];

export const seedEquipes: Equipe[] = [
  { id: 'eq-1', nom: 'Équipe Crédit Classique Dakar', agenceId: 'ag-1', responsableId: 'u-7', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-2', nom: 'Équipe Crédit Collecte Dakar', agenceId: 'ag-1', responsableId: 'u-35', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-3', nom: 'Équipe Commerciale Collecte Dakar', agenceId: 'ag-1', responsableId: 'u-14', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-4', nom: 'Équipe Bureau Direct Dakar', agenceId: 'ag-1', responsableId: 'u-34', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-5', nom: 'Équipe Crédit Classique Congo', agenceId: 'ag-2', responsableId: 'u-38', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-6', nom: 'Équipe Crédit Collecte Congo', agenceId: 'ag-2', responsableId: 'u-62', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-7', nom: 'Équipe Commerciale Collecte Congo', agenceId: 'ag-2', responsableId: 'u-45', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-8', nom: 'Équipe Bureau Direct Congo', agenceId: 'ag-2', responsableId: 'u-62', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-9', nom: 'Équipe Crédit Classique Akwa', agenceId: 'ag-10', responsableId: 'u-63', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-10', nom: 'Équipe Crédit Collecte Akwa', agenceId: 'ag-10', responsableId: 'u-91', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-11', nom: 'Équipe Commerciale Collecte Akwa', agenceId: 'ag-10', responsableId: 'u-72', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-12', nom: 'Équipe Bureau Direct Akwa', agenceId: 'ag-10', responsableId: 'u-90', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-13', nom: 'Équipe Crédit Classique Mokolo', agenceId: 'ag-3', responsableId: 'u-94', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-14', nom: 'Équipe Crédit Collecte Mokolo', agenceId: 'ag-3', responsableId: 'u-120', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-15', nom: 'Équipe Commerciale Collecte Mokolo', agenceId: 'ag-3', responsableId: 'u-102', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-16', nom: 'Équipe Bureau Direct Mokolo', agenceId: 'ag-3', responsableId: 'u-119', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-17', nom: 'Équipe Crédit Classique Djemoun', agenceId: 'ag-4', responsableId: 'u-123', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-18', nom: 'Équipe Crédit Collecte Djemoun', agenceId: 'ag-4', responsableId: 'u-154', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-19', nom: 'Équipe Commerciale Collecte Djemoun', agenceId: 'ag-4', responsableId: 'u-133', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-20', nom: 'Équipe Bureau Direct Djemoun', agenceId: 'ag-4', responsableId: 'u-153', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-21', nom: 'Équipe Crédit Classique Bonaberi', agenceId: 'ag-5', responsableId: 'u-156', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-22', nom: 'Équipe Crédit Collecte Bonaberi', agenceId: 'ag-5', responsableId: 'u-178', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-23', nom: 'Équipe Commerciale Collecte Bonaberi', agenceId: 'ag-5', responsableId: 'u-160', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-24', nom: 'Équipe Bureau Direct Bonaberi', agenceId: 'ag-5', responsableId: 'u-177', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-25', nom: 'Équipe Crédit Classique Dschang', agenceId: 'ag-6', responsableId: 'u-181', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-26', nom: 'Équipe Crédit Collecte Dschang', agenceId: 'ag-6', responsableId: 'u-207', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-27', nom: 'Équipe Commerciale Collecte Dschang', agenceId: 'ag-6', responsableId: 'u-189', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-28', nom: 'Équipe Bureau Direct Dschang', agenceId: 'ag-6', responsableId: 'u-206', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-29', nom: 'Équipe Crédit Classique Etoudi', agenceId: 'ag-7', responsableId: 'u-209', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-30', nom: 'Équipe Crédit Collecte Etoudi', agenceId: 'ag-7', responsableId: 'u-231', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-31', nom: 'Équipe Commerciale Collecte Etoudi', agenceId: 'ag-7', responsableId: 'u-218', createdAt: '2025-01-05T00:00:00Z' },
  { id: 'eq-32', nom: 'Équipe Bureau Direct Etoudi', agenceId: 'ag-7', responsableId: 'u-230', createdAt: '2025-01-05T00:00:00Z' },
];

export const seedAgents: Agent[] = [
  { id: 'agt-1', utilisateurId: 'u-1', matricule: 'AGT-001', secteur: 'Zone Akwa-Nord',  latitude: 4.0560, longitude: 9.7010, dernierePositionAt: '2026-05-22T08:12:00Z' },
  { id: 'agt-2', utilisateurId: 'u-2', matricule: 'AGT-002', secteur: 'Zone Akwa-Sud',   latitude: 4.0448, longitude: 9.7068, dernierePositionAt: '2026-05-22T08:47:00Z' },
  { id: 'agt-3', utilisateurId: 'u-3', matricule: 'AGT-003', secteur: 'Zone Bonanjo',    latitude: 4.0395, longitude: 9.6945, dernierePositionAt: '2025-11-10T08:45:00Z' },
];

// ─── Marketing ───────────────────────────────────────────────────────────────

export const seedProspects: Prospect[] = [
  { id: 'prs-1', nom: 'Ondoa', prenom: 'Céline', telephone: '677001122', statut: 'interesse', produitInteretId: 'pr-1', commercialId: 'u-1', notes: 'Très intéressée par le DAT 12 mois', createdAt: '2025-05-01T00:00:00Z', updatedAt: '2025-05-15T00:00:00Z' },
  { id: 'prs-2', nom: 'Bibi', prenom: 'Roland', telephone: '699223344', statut: 'contacte', produitInteretId: 'pr-2', commercialId: 'u-2', notes: '', createdAt: '2025-05-08T00:00:00Z', updatedAt: '2025-05-08T00:00:00Z' },
  { id: 'prs-3', nom: 'Mbah', prenom: 'Grâce', telephone: '655445566', statut: 'nouveau', produitInteretId: 'pr-5', commercialId: 'u-1', notes: 'Agricultrice zone périurbaine', createdAt: '2025-05-18T00:00:00Z', updatedAt: '2025-05-18T00:00:00Z' },
  { id: 'prs-4', nom: 'Ngo', prenom: 'Isabelle', telephone: '677667788', statut: 'negocie', produitInteretId: 'pr-3', commercialId: 'u-3', notes: 'Discutons tarif famille', createdAt: '2025-04-20T00:00:00Z', updatedAt: '2025-05-10T00:00:00Z' },
  { id: 'prs-5', nom: 'Fouda', prenom: 'Hervé', telephone: '699889900', statut: 'perdu', produitInteretId: 'pr-1', commercialId: 'u-2', notes: 'Parti chez concurrent', createdAt: '2025-04-10T00:00:00Z', updatedAt: '2025-04-28T00:00:00Z' },
];

export const seedClients: Client[] = [
  { id: 'cl-1', prospectId: null, nom: 'Zambo', prenom: 'Paul', telephone: '699001122', email: 'p.zambo@cecaw.cm', adresse: 'Akwa Nord, Douala', agenceId: 'ag-1', commercialId: 'u-1', statut: 'actif', createdAt: '2025-01-20T00:00:00Z' },
  { id: 'cl-2', prospectId: null, nom: "Eto'o", prenom: 'Samuel', telephone: '655889900', email: 's.etoo@cecaw.cm', adresse: 'Akwa, Douala', agenceId: 'ag-1', commercialId: 'u-2', statut: 'actif', createdAt: '2025-02-05T00:00:00Z' },
  { id: 'cl-3', prospectId: null, nom: 'Moukoko', prenom: 'Hélène', telephone: '677445566', email: 'h.moukoko@cecaw.cm', adresse: 'Bonanjo, Douala', agenceId: 'ag-2', commercialId: 'u-3', statut: 'actif', createdAt: '2025-03-01T00:00:00Z' },
  { id: 'cl-4', prospectId: null, nom: 'Ngando', prenom: 'Pierre', telephone: '699223344', email: '', adresse: 'Bassa, Douala', agenceId: 'ag-3', commercialId: 'u-1', statut: 'inactif', createdAt: '2025-01-10T00:00:00Z' },
];

export const seedComptes: CompteClient[] = [
  { id: 'cp-1', numero: 'ACC-2025-001', clientId: 'cl-1', produitId: 'pr-1', solde: 450000, statut: 'actif', dateOuverture: '2025-01-20', createdAt: '2025-01-20T00:00:00Z' },
  { id: 'cp-2', numero: 'ACC-2025-002', clientId: 'cl-1', produitId: 'pr-3', solde: 12000, statut: 'actif', dateOuverture: '2025-02-01', createdAt: '2025-02-01T00:00:00Z' },
  { id: 'cp-3', numero: 'ACC-2025-003', clientId: 'cl-2', produitId: 'pr-2', solde: 1250000, statut: 'actif', dateOuverture: '2025-02-05', createdAt: '2025-02-05T00:00:00Z' },
  { id: 'cp-4', numero: 'ACC-2025-004', clientId: 'cl-3', produitId: 'pr-1', solde: 80000, statut: 'actif', dateOuverture: '2025-03-01', createdAt: '2025-03-01T00:00:00Z' },
  { id: 'cp-5', numero: 'ACC-2025-005', clientId: 'cl-4', produitId: 'pr-5', solde: 0, statut: 'suspendu', dateOuverture: '2025-01-15', createdAt: '2025-01-15T00:00:00Z' },
];

export const seedTransactions: Transaction[] = [
  { id: 'tx-1', compteId: 'cp-1', type: 'credit', montant: 200000, soldeAvant: 250000, soldeApres: 450000, motif: 'Versement mensuel mai', agentId: 'agt-1', createdAt: '2025-05-10T09:00:00Z' },
  { id: 'tx-2', compteId: 'cp-1', type: 'credit', montant: 150000, soldeAvant: 100000, soldeApres: 250000, motif: 'Versement mensuel avril', agentId: 'agt-1', createdAt: '2025-04-10T09:30:00Z' },
  { id: 'tx-3', compteId: 'cp-1', type: 'debit', montant: 100000, soldeAvant: 200000, soldeApres: 100000, motif: 'Retrait partiel', agentId: 'agt-2', createdAt: '2025-03-22T14:00:00Z' },
  { id: 'tx-4', compteId: 'cp-3', type: 'credit', montant: 500000, soldeAvant: 750000, soldeApres: 1250000, motif: 'Apport capital supplémentaire', agentId: 'agt-2', createdAt: '2025-05-05T11:00:00Z' },
  { id: 'tx-5', compteId: 'cp-4', type: 'credit', montant: 80000, soldeAvant: 0, soldeApres: 80000, motif: 'Ouverture de compte', agentId: 'agt-3', createdAt: '2025-03-01T10:00:00Z' },
];

// ─── Collecte ────────────────────────────────────────────────────────────────

export const seedObjectifs: Objectif[] = [
  {
    id: 'obj-1',
    titre: 'Recrutement DAT — Mai 2025',
    produitId: 'pr-1',
    cible: 10,
    unite: 'clients',
    periodicite: 'mois',
    dateDebut: '2025-05-01',
    dateFin: '2025-05-31',
    assignationType: 'equipe',
    equipeId: 'eq-1',
    agentIds: [],
    realise: 6,
    statut: 'en_cours',
    createdAt: '2025-04-30T00:00:00Z',
    createdById: 'u-4',
  },
  {
    id: 'obj-2',
    titre: 'Collecte Épargne Standard — Mvondo',
    produitId: 'pr-2',
    cible: 500000,
    unite: 'montant',
    periodicite: 'semaine',
    dateDebut: '2025-05-19',
    dateFin: '2025-05-25',
    assignationType: 'agents',
    equipeId: null,
    agentIds: ['agt-1'],
    realise: 320000,
    statut: 'en_cours',
    createdAt: '2025-05-18T00:00:00Z',
    createdById: 'u-4',
  },
  {
    id: 'obj-3',
    titre: 'Prospection Micro-crédit Agricole',
    produitId: 'pr-5',
    cible: 5,
    unite: 'clients',
    periodicite: 'mois',
    dateDebut: '2025-05-01',
    dateFin: '2025-05-31',
    assignationType: 'agents',
    equipeId: null,
    agentIds: ['agt-1', 'agt-3'],
    realise: 5,
    statut: 'atteint',
    createdAt: '2025-04-30T00:00:00Z',
    createdById: 'u-4',
  },
];
